services:

  # Laravel Application
  app:
    image: oors-app
    build:
      dockerfile: docker/app.Dockerfile
    container_name: ${APP_CONTAINER}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - TZ="Asia/Manila"
    volumes:
      - type: bind
        source: ./
        target: /var/www/app-source/
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - oors_network

  # Web Server Nginx
  nginx:
    build:
      dockerfile: docker/nginx.Dockerfile
    container_name: ${NGINX_CONTAINER}
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      - TZ="Asia/Manila"
    volumes:
      - type: bind
        source: ./
        target: /var/www/app-source/
    restart: unless-stopped
    ports:
      - ${NGINX_EXPOSED_PORT}:80
    networks:
      - oors_network
    depends_on:
      - app

networks:
 oors_network:
  driver: bridge